#!/usr/bin/env python
# -*- coding: utf-8 -*-

__description__ = 'Convert a line of words into a slug'

# ---------------------------------------------------------------------------
# Standard imports:
import argparse
import string
import sys
from datetime import date
from unidecode import unidecode

# Third party imports

# Local imports

# ---------------------------------------------------------------------------


def sluggify(text, prefix):
    slug_parts = [prefix]
    text = unidecode('-'.join(text.split()))
    passthrough = string.ascii_lowercase + string.digits + '-'
    for c in text.lower():
        if c in passthrough:
            slug_parts.append(c)
        elif c not in string.punctuation:
            slug_parts.append('#')
    return "".join(slug_parts)

def get_date(format='%Y%m%d'):
    return date.today().strftime(format)

def parse_args(argv):
    """ Parse and validate command line arguments """
    parser = argparse.ArgumentParser(description=__description__)
    parser.add_argument('words', metavar='WORD', nargs='+', help='Words to sluggify')
    parser.add_argument('-d','--date', action='store_true', help='Prepend date in YYYYMMDD format')

    args = parser.parse_args(argv[1:])
    args.words = unicode(" ".join(args.words), "UTF-8")
    return args

def main(argv=[__name__]):
    """ Run this program """
    args = parse_args(argv)
    try:
        sdate = (get_date() + '_') if args.date else ''
        print sluggify(args.words, sdate)

    except KeyboardInterrupt:
        sys.exit(-1)

if __name__ == '__main__':
    sys.exit(main(sys.argv) or 0)
